name: lab03_frontend
description: Lab 03 REST API Chat Frontend

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0
  build_runner: ^2.2.0
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true 